[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_template = "BNdAHQMniLicundk1jo4qKWyNr9C8bK7oUrzgSwoSGmZ"
hpl_nectar_missions = "BNdAHQMniLicundk1jo4qKWyNr9C8bK7oUrzgSwoSGmZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
