name: Cache dependencies

runs:
  using: composite
  steps:
    - name: Cache Cargo Binaries
      uses: actions/cache@v3
      with:
        key: "hive-control"
        path: |
          ~/.cargo
          ./node_modules
