[package]
name = "hpl-nectar-missions"
version = "0.0.8"
description = "Honeycomb protocol library nectar utilities missions program"
author = ['Sultan Nadeem <sultanndilaram@gmail.com>']
edition = "2021"
license = "MIT"


[lib]
crate-type = ["cdylib", "lib"]
name = "hpl_nectar_missions"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
hpl-utils = "0.1.6"
hpl-hive-control = { version="0.0.99", features = ["cpi"] }
hpl-currency-manager = { version="0.0.2", features = ["cpi"] }
hpl-nectar-staking = { version="0.0.42", path="../hpl-nectar-staking", features = ["cpi"] }
