[package]
name = "hpl-nectar-missions"
version = "0.0.34"
description = "Honeycomb protocol library nectar utilities missions program"
author = ['Sultan Nadeem <sultanndilaram@gmail.com>']
edition = "2021"
license = "MIT"


[lib]
crate-type = ["cdylib", "lib"]
name = "hpl_nectar_missions"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
getrandom = { version = "0.2.9", features = ["custom"] }
solana-program = "=1.14.17"
winnow = "=0.4.1"
toml_datetime = "=0.6.1"
hpl-utils = "0.1.7"
hpl-hive-control = { version="0.1.17", features = ["cpi"] }
hpl-currency-manager = { version="0.0.37", features = ["cpi"] }
hpl-nectar-staking = { version="0.0.68", path="../hpl-nectar-staking", features = ["cpi"] }
spl-account-compression = { version="0.1.8", features=["cpi"] }
